from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[1]
RECIPE_XLSX = ROOT / "Excel File" / "Vista Component Recipie New.xlsx"
OUTPUT_SQL = ROOT / "supabase" / "migrations" / "009_refresh_recipe_catalog.sql"

BLIND_TYPE_MAP = {
    "Roller W/o Headrail Parts": "Roller Blinds Without Headrail",
    "Roller with Headrail Parts": "Roller Blinds With Headrail",
    "Sheer Dimout Plain Cassette Parts": "Sheer Dimout Blinds Classic Mechanism with Plain Cassette",
    "Sheer Dimout Decorative Cassette Parts": "Sheer Dimout Blinds Classic Mechanism with Decorative Cassette",
    "S Contour Parts": "S-Contour Blinds",
    "Roller with Plain Cassette": "Roller Blinds With Plain Cassette",
    "Roller with Decorative Cassette": "Roller Blinds With Decorative Cassette",
}

SECTION_CATEGORY_MAP = {
    "Roller W/o Headrail Parts": ["roller w/o headrail parts"],
    "Roller with Headrail Parts": ["roller with headrail parts"],
    "Sheer Dimout Plain Cassette Parts": ["sheer dimout plain cassette parts"],
    "Sheer Dimout Decorative Cassette Parts": ["sheer dimout decorative cassette parts"],
    "S Contour Parts": ["s contour parts"],
    "Roller with Plain Cassette": [
        "roller with plain cassette",
        "roller with headrail parts",
        "sheer dimout plain cassette parts",
    ],
    "Roller with Decorative Cassette": [
        "roller with decorative cassette",
        "roller with headrail parts",
        "sheer dimout plain cassette parts",
        "sheer dimout decorative cassette parts",
    ],
}


def sql_text(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def normalize_component(code: str) -> str:
    text = str(code or "").strip()
    if "-" in text:
        text = text.split("-", 1)[1]
    return " ".join(text.replace('"', "").replace("'", "").replace(".", "").lower().split())


def parse_sections():
    wb = load_workbook(RECIPE_XLSX, data_only=True)
    ws = wb[wb.sheetnames[0]]

    sections: list[tuple[str, list[dict]]] = []
    current_name = None
    current_rows: list[dict] = []
    for row in ws.iter_rows(values_only=True):
        stock_category, code, qty, note = (list(row[:4]) + [None] * 4)[:4]
        if stock_category == "Stock Category" and code == "FINAL PRODUCT CODE":
            if current_name and current_rows:
                sections.append((current_name, current_rows))
            current_name = None
            current_rows = []
            continue
        if not stock_category or not code:
            continue
        current_name = str(stock_category).strip()
        qty_num = None if qty in (None, "") else float(qty)
        current_rows.append({
            "stock_category": current_name,
            "code": str(code).strip(),
            "component_name": str(code).strip().split("-", 1)[1].strip() if "-" in str(code).strip() else str(code).strip(),
            "normalized_component": normalize_component(str(code).strip()),
            "quantity": qty_num,
            "is_width_dependent": bool(note and "width" in str(note).lower()),
        })
    if current_name and current_rows:
        sections.append((current_name, current_rows))
    return sections


def build_catalog():
    catalog: OrderedDict[str, dict] = OrderedDict()
    for stock_category, rows in parse_sections():
        blind_type = BLIND_TYPE_MAP.get(stock_category)
        if not blind_type:
            continue
        entry = catalog.setdefault(blind_type, {
            "name": blind_type,
            "blind_type": blind_type,
            "description": "Imported from Vista Component Recipie New.xlsx",
            "notes": stock_category,
            "inventory_categories": SECTION_CATEGORY_MAP.get(stock_category, []),
            "source_sections": [],
            "items": OrderedDict(),
        })
        entry["source_sections"].append(stock_category)
        for row in rows:
            key = row["normalized_component"]
            entry["items"][key] = row
    return catalog


def render_sql():
    catalog = build_catalog()
    lines = [
        "-- ============================================================",
        "-- Recipe catalog refresh from updated Vista Component Recipie New.xlsx",
        "-- Generated by scripts/generate_recipe_refresh_sql.py",
        "-- Workbook snapshot: 2026-05-07",
        "-- Note: current workbook contains 8 sections, with one duplicate",
        "-- Roller with Headrail section merged into one canonical blind recipe.",
        "-- ============================================================",
        "",
        "BEGIN;",
        "",
    ]

    for blind_type, recipe in catalog.items():
        note = ", ".join(dict.fromkeys(recipe["source_sections"]))
        lines.append(
            f"INSERT INTO public.product_recipes (name, blind_type, description, is_active, notes) "
            f"VALUES ({sql_text(recipe['name'])}, {sql_text(recipe['blind_type'])}, {sql_text(recipe['description'])}, true, {sql_text(note)}) "
            f"ON CONFLICT DO NOTHING;"
        )
        lines.append(
            f"DELETE FROM public.recipe_items WHERE recipe_id IN (SELECT id FROM public.product_recipes WHERE blind_type = {sql_text(blind_type)});"
        )
        sort_order = 1
        for item in recipe["items"].values():
            qty = "1" if item["is_width_dependent"] else str(item["quantity"] or 0)
            preferred_categories = recipe["inventory_categories"] or []
            order_clauses = []
            for index, category in enumerate(preferred_categories):
                order_clauses.append(
                    f"WHEN c.normalized_name = {sql_text(category)} THEN {index}"
                )
            order_sql = " ".join(order_clauses) if order_clauses else ""
            lines.append(
                f"WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = {sql_text(blind_type)} LIMIT 1), "
                f"v AS (SELECT v.id, v.unit, v.name FROM public.inv_variants v "
                f"JOIN public.inv_products p ON p.id = v.product_id "
                f"JOIN public.inv_categories c ON c.id = p.category_id "
                f"WHERE v.normalized_name = {sql_text(item['normalized_component'])} "
                f"ORDER BY CASE {order_sql} ELSE 999 END, c.name, p.name, v.name LIMIT 1) "
                f"INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) "
                f"SELECT r.id, v.id, COALESCE(v.name, {sql_text(item['component_name'])}), {qty}, {'true' if item['is_width_dependent'] else 'false'}, {sort_order} "
                f"FROM r JOIN v ON true;"
            )
            sort_order += 1
        lines.append("")

    lines.extend([
        "COMMIT;",
        "",
        "SELECT",
        "  (SELECT COUNT(*) FROM public.product_recipes) AS product_recipes,",
        "  (SELECT COUNT(*) FROM public.recipe_items) AS recipe_items,",
        "  (SELECT COUNT(*) FROM public.recipe_items WHERE variant_id IS NULL) AS unmatched_recipe_items;",
        "",
    ])
    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT_SQL.write_text(render_sql(), encoding="utf-8")
    print(f"Wrote {OUTPUT_SQL}")
