-- ============================================================
-- Supporting workbook import
-- Sources: Vista Component Recipie New.xlsx and Tracks.xlsx
-- - Component recipe workbook imports into product_recipes/recipe_items.
-- - Tracks.xlsx is a set of printable production templates, not stock rows.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.fg_stock (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  purchase_date DATE,
  purchase_cost NUMERIC(12,2),
  quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT 'pcs',
  bill_no TEXT,
  supplier TEXT,
  notes TEXT,
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS fg_stock_code_key ON public.fg_stock (LOWER(code));
ALTER TABLE IF EXISTS public.order_items ADD COLUMN IF NOT EXISTS fg_stock_id UUID REFERENCES public.fg_stock(id);
ALTER TABLE public.fg_stock DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.product_recipes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  blind_type TEXT,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.product_recipes ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.product_recipes ADD COLUMN IF NOT EXISTS blind_type TEXT;
ALTER TABLE public.product_recipes ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public.product_recipes ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.product_recipes ADD COLUMN IF NOT EXISTS notes TEXT;

CREATE TABLE IF NOT EXISTS public.recipe_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recipe_id UUID NOT NULL REFERENCES public.product_recipes(id) ON DELETE CASCADE,
  variant_id UUID REFERENCES public.inv_variants(id) ON DELETE SET NULL,
  component_name TEXT,
  quantity_per_unit NUMERIC NOT NULL DEFAULT 0,
  is_width_dependent BOOLEAN NOT NULL DEFAULT false,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS variant_id UUID REFERENCES public.inv_variants(id) ON DELETE SET NULL;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS component_name TEXT;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS quantity_per_unit NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS is_width_dependent BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.recipe_items ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

ALTER TABLE public.product_recipes DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_items DISABLE ROW LEVEL SECURITY;

DELETE FROM public.recipe_items;
DELETE FROM public.product_recipes;

INSERT INTO public.product_recipes (name, blind_type, description, is_active, notes) VALUES ('Roller Blinds Without Headrail', 'Roller Blinds Without Headrail', 'Imported from Vista Component Recipie New.xlsx', true, 'Roller W/o Headrail Parts');
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'aluminium roller tube (4.575) 38 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALUMINIUM ROLLER TUBE (4.575) 38 MM', 1, true, 1 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'alu bottom rail (4.575 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU BOTTOM RAIL (4.575 MTR)', 1, true, 2 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'control unit ks 38 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CONTROL UNIT KS 38 MM', 1.0, false, 3 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'double sided fixon tape 12mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Double Sided Fixon Tape 12MM', 4.0, false, 4 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'cord weight' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CORD WEIGHT', 1.0, false, 5 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'connector - bush type''' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Connector - Bush Type''', 1.0, false, 6 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'bottom rail end cap''' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Bottom Rail End Cap''', 2.0, false, 7 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'operating ball chain''' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Operating Ball Chain''', 4.0, false, 8 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'pvc insert 15mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'PVC INSERT 15MM', 2.0, false, 9 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'pvc insert 12 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'PVC INSERT 12 MM', 2.0, false, 10 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'chain stopper' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Chain Stopper', 1.0, false, 11 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'royal screw 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ROYAL SCREW 8X50', 7.0, false, 12 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'royal plug 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ROYAL PLUG 8X50', 7.0, false, 13 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds Without Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller w/o headrail parts' AND v.normalized_name = 'poly tube 5"' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'POLY TUBE 5"', 2.0, false, 14 FROM r LEFT JOIN v ON true;

INSERT INTO public.product_recipes (name, blind_type, description, is_active, notes) VALUES ('Roller Blinds With Headrail', 'Roller Blinds With Headrail', 'Imported from Vista Component Recipie New.xlsx', true, 'Roller with Headrail Parts');
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'alu roller tube 39mm (4.575 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU ROLLER TUBE 39MM (4.575 MTR)', 1, true, 1 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'alu. round bottom rail(4.57 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU. ROUND BOTTOM RAIL(4.57 MTR)', 1, true, 2 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'alu.headrail patti (4.575 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU.HEADRAIL PATTI (4.575 MTR)', 1, true, 3 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'control unit 38mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CONTROL UNIT 38MM', 1.0, false, 4 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'double sided fixon tape 12mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Double Sided Fixon Tape 12MM', 4.0, false, 5 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'cord weight' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CORD WEIGHT', 1.0, false, 6 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'connector - bush type''' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Connector - Bush Type''', 1.0, false, 7 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'bottom rail end cap''' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Bottom Rail End Cap''', 2.0, false, 8 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'operating ball chain' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Operating Ball Chain', 4.0, false, 9 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'pvc insert 15mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'PVC INSERT 15MM', 2.0, false, 10 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'pvc insert 12 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'PVC INSERT 12 MM', 2.0, false, 11 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'chain stopper' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Chain Stopper', 1.0, false, 12 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'l bracket.' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'L BRACKET.', 4.0, false, 13 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'p. clip' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'P. CLIP', 4.0, false, 14 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'royal plug 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ROYAL PLUG 8X50', 7.0, false, 15 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'royal screw 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ROYAL SCREW 8X50', 7.0, false, 16 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Roller Blinds With Headrail' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'roller with headrail parts' AND v.normalized_name = 'poly tube 5"' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'POLY TUBE 5"', 2.0, false, 17 FROM r LEFT JOIN v ON true;

INSERT INTO public.product_recipes (name, blind_type, description, is_active, notes) VALUES ('Sheer Dimout Blinds Classic Mechanism with Plain Cassette', 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette', 'Imported from Vista Component Recipie New.xlsx', true, 'Sheer Dimout Plain Cassette Parts');
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'alu roller tube 39mm (4.575 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU ROLLER TUBE 39MM (4.575 MTR)', 1, true, 1 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'alu. round bottom rail(4.57 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU. ROUND BOTTOM RAIL(4.57 MTR)', 1, true, 2 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'alu. triangle type bottom rail' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU. TRIANGLE TYPE BOTTOM RAIL', 1, true, 3 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'alu. headrail with cover' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Alu. Headrail with Cover', 1, true, 4 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'control unit ks 38 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CONTROL UNIT KS 38 MM', 1.0, false, 5 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'end less chain' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'End Less Chain', 1.0, false, 6 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'end cap round bottom rail' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'END CAP ROUND BOTTOM RAIL', 2.0, false, 7 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'end cap triangular bottom rail' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'END CAP TRIANGULAR BOTTOM RAIL', 2.0, false, 8 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'metal end cap' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Metal End Cap', 1.0, false, 9 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'ceilling bracket''' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CEILLING BRACKET''', 3.0, false, 10 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'cord weight' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CORD WEIGHT', 1.0, false, 11 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'royal screw 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ROYAL SCREW 8X50', 7.0, false, 12 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'royal plug 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ROYAL PLUG 8X50', 7.0, false, 13 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'p.v.c insert 10mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'P.V.C INSERT 10MM', 2.0, false, 14 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'pvc insert 12 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'PVC INSERT 12 MM', 2.0, false, 15 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'double sided fixon tape 12mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Double Sided Fixon Tape 12MM', 4.0, false, 16 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Plain Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout plain cassette parts' AND v.normalized_name = 'poly tube 5"' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'POLY TUBE 5"', 2.0, false, 17 FROM r LEFT JOIN v ON true;

INSERT INTO public.product_recipes (name, blind_type, description, is_active, notes) VALUES ('Sheer Dimout Blinds Classic Mechanism with Decorative Cassette', 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette', 'Imported from Vista Component Recipie New.xlsx', true, 'Sheer Dimout Decorative Cassette Parts');
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'alu roller tube 39mm (4.575 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU ROLLER TUBE 39MM (4.575 MTR)', 1, true, 1 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'alu. round bottom rail(4.57 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU. ROUND BOTTOM RAIL(4.57 MTR)', 1, true, 2 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'alu. u type bottom rail' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ALU. U TYPE BOTTOM RAIL', 1, true, 3 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'control unit.' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CONTROL UNIT.', 1.0, false, 4 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'end less chain' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'End Less Chain', 1.0, false, 5 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'end cap round bottom rail' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'END CAP ROUND BOTTOM RAIL', 2.0, false, 6 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'end cap u type bottom rail' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'END CAP U TYPE BOTTOM RAIL', 2.0, false, 7 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'metal end cap' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Metal End Cap', 1.0, false, 8 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'ceilling bracket''' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CEILLING BRACKET''', 3.0, false, 9 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'cord weight' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'CORD WEIGHT', 1.0, false, 10 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'p.v.c insert 10mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'P.V.C INSERT 10MM', 2.0, false, 11 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'pvc insert 12 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'PVC INSERT 12 MM', 2.0, false, 12 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'double sided fixon tape 12mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Double Sided Fixon Tape 12MM', 4.0, false, 13 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'poly tube 5"' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'POLY TUBE 5"', 2.0, false, 14 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'alu. headrail with cover' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Alu. Headrail with Cover', 2.0, false, 15 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'chain stopper' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Chain Stopper', 1.0, false, 16 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'pvc sheet width 87 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'PVC SHEET WIDTH 87 MM', 2.0, false, 17 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'royal screw 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ROYAL SCREW 8X50', 7.0, false, 18 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'Sheer Dimout Blinds Classic Mechanism with Decorative Cassette' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 'sheer dimout decorative cassette parts' AND v.normalized_name = 'royal plug 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'ROYAL PLUG 8X50', 7.0, false, 19 FROM r LEFT JOIN v ON true;

INSERT INTO public.product_recipes (name, blind_type, description, is_active, notes) VALUES ('S-Contour Blinds', 'S-Contour Blinds', 'Imported from Vista Component Recipie New.xlsx', true, 'S Contour Parts');
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-alu roller tube 39mm (4.575 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-ALU ROLLER TUBE 39MM (4.575 MTR)', 1, true, 1 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-alu bottom rail (4.575 mtr)' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-ALU BOTTOM RAIL (4.575 MTR)', 1, true, 2 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-alu. headrail with cover' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-Alu. Headrail with Cover', 1, true, 3 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-control unit 38mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-CONTROL UNIT 38MM', 1.0, false, 4 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-end less chain' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-End Less Chain', 1.0, false, 5 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-bottom rail end cap''' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-Bottom Rail End Cap''', 2.0, false, 6 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-chain stopper' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-Chain Stopper', 1.0, false, 7 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-metal end cap' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-Metal End Cap', 1.0, false, 8 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-pvc sheet width 87 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-PVC SHEET WIDTH 87 MM', 2.0, false, 9 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-ceiling bracket' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-CEILING BRACKET', 3.0, false, 10 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-cord weight' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-CORD WEIGHT', 1.0, false, 11 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-royal screw 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-ROYAL SCREW 8X50', 7.0, false, 12 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-royal plug 8x50' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-ROYAL PLUG 8X50', 7.0, false, 13 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-pvc insert 12 mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-PVC INSERT 12 MM', 2.0, false, 14 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-double sided fixon tape 12mm' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-Double Sided Fixon Tape 12MM', 4.0, false, 15 FROM r LEFT JOIN v ON true;
WITH r AS (SELECT id FROM public.product_recipes WHERE blind_type = 'S-Contour Blinds' LIMIT 1), v AS (SELECT v.id FROM public.inv_variants v JOIN public.inv_products p ON p.id = v.product_id JOIN public.inv_categories c ON c.id = p.category_id WHERE c.normalized_name = 's contour parts' AND v.normalized_name = 'contour-poly tube 5"' LIMIT 1) INSERT INTO public.recipe_items (recipe_id, variant_id, component_name, quantity_per_unit, is_width_dependent, sort_order) SELECT r.id, v.id, 'Contour-POLY TUBE 5"', 2.0, false, 16 FROM r LEFT JOIN v ON true;

COMMIT;

SELECT
  (SELECT COUNT(*) FROM public.product_recipes) AS product_recipes,
  (SELECT COUNT(*) FROM public.recipe_items) AS recipe_items,
  (SELECT COUNT(*) FROM public.recipe_items WHERE variant_id IS NULL) AS unmatched_recipe_items,
  (SELECT COUNT(*) FROM public.fg_stock) AS finished_goods;
