-- Import master structure interpreted from Excel File/Vista-Inflow Data to Rishi.xlsx.
-- Source rows are stock/RM/FG heavy; this migration imports structure labels only.
-- Generated paths: 396 (fabric=255, parts=123, tracks=15, motors=3, ignored=3).

DO $$
DECLARE
  rec record;
  v_page_id uuid;
  v_parent_id uuid;
  v_node_id uuid;
  v_name text;
  v_normalized text;
  v_idx integer;
BEGIN
  FOR rec IN
    SELECT * FROM (VALUES
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Bamberg', '01']::text[], 10),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Bamberg', '02']::text[], 20),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Bamberg', '03']::text[], 30),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Bamberg', '04']::text[], 40),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Bamberg', '05']::text[], 50),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Cloudnine', 'CN-01 White']::text[], 60),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Cloudnine', 'CN-02 Ivory']::text[], 70),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Cloudnine', 'CN-03 Grey']::text[], 80),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'DS Opaque', 'Linen']::text[], 90),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'DS Opaque', 'Grey']::text[], 100),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'DS Opaque', 'White']::text[], 110),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'DS Opaque', 'Fawn']::text[], 120),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'DS Opaque', 'Champagne']::text[], 130),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Elena', '01']::text[], 140),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Elena', '02']::text[], 150),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Elena', '04']::text[], 160),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Elena', '05']::text[], 170),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Murano', 'Opaque-01']::text[], 180),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Murano', 'Opaque-03']::text[], 190),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Murano', 'Opaque-05']::text[], 200),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Murano', 'Opaque-07']::text[], 210),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '01']::text[], 220),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '02']::text[], 230),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '03']::text[], 240),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '04']::text[], 250),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '05']::text[], 260),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '06']::text[], 270),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '07']::text[], 280),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '08']::text[], 290),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '09']::text[], 300),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '10']::text[], 310),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Serene', 'Opaque-01 White']::text[], 320),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Serene', 'Opaque-02 Beige']::text[], 330),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Serene', 'Opaque-03 Sand']::text[], 340),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Serene', 'Opaque-04 Grey']::text[], 350),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Skyler', '01']::text[], 360),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Skyler', '02']::text[], 370),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Skyler', '04']::text[], 380),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Skyler', '05']::text[], 390),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Skyler', '06']::text[], 400),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Venice', 'Opaque-01']::text[], 410),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Venice', 'Opaque-02']::text[], 420),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Venice', 'Opaque-03']::text[], 430),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Venice', 'Opaque-05']::text[], 440),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Venice', 'Opaque-06']::text[], 450),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Violet', '01']::text[], 460),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Violet', '02']::text[], 470),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Violet', '03']::text[], 480),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Violet', '04']::text[], 490),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Violet', '05']::text[], 500),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '1%', '111 White']::text[], 510),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '1%', '112 Beige']::text[], 520),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '1%', '113 Grey']::text[], 530),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '3%', '331 White']::text[], 540),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '3%', '332 Beige']::text[], 550),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '3%', '334 Grey']::text[], 560),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '551 White']::text[], 570),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '552 Fawn']::text[], 580),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '554 Grey']::text[], 590),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '556 Black Grey']::text[], 600),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '557 Light Grey']::text[], 610),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Mellow', 'ML-01 White']::text[], 620),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Mellow', 'ML-02 Ivory']::text[], 630),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Mellow', 'ML-03 Beige']::text[], 640),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Mellow', 'ML-04 Chocolate']::text[], 650),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Mellow', 'ML-05 Grey']::text[], 660),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Surge', 'SG-01']::text[], 670),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Surge', 'SG-04']::text[], 680),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Surge', 'SG-05']::text[], 690),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Serene NBO', '01 White']::text[], 700),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Serene NBO', '02 Beige']::text[], 710),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Serene NBO', '03 Sand']::text[], 720),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Serene NBO', '04 Grey']::text[], 730),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-01']::text[], 740),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-03']::text[], 750),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-09']::text[], 760),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-16']::text[], 770),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-31']::text[], 780),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-33']::text[], 790),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Denver', 'SDDR-02']::text[], 800),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Denver', 'SDDR-03']::text[], 810),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Denver', 'SDDR-04']::text[], 820),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Novel', 'SDNB-01']::text[], 830),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Novel', 'SDNB-02']::text[], 840),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Novel', 'SDNB-03']::text[], 850),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Novel', 'SDNB-04']::text[], 860),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Novel', 'SDNB-05']::text[], 870),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Novel', 'SDNB-06']::text[], 880),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Sahara', 'SDSR-01']::text[], 890),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Sahara', 'SDSR-03']::text[], 900),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Sahara', 'SDSR-04']::text[], 910),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Sahara', 'SDSR-05']::text[], 920),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Sahara', 'SDSR-07']::text[], 930),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Thar', 'SDTH-03']::text[], 940),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Thar', 'SDTH-04']::text[], 950),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Thar', 'SDTH-05']::text[], 960),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Thar', 'SDTH-06']::text[], 970),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Alchemy', 'SDAM-01']::text[], 980),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Alchemy', 'SDAM-02']::text[], 990),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Alchemy', 'SDAM-03']::text[], 1000),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Alchemy', 'SDAM-07']::text[], 1010),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Alchemy', 'SDAM-08']::text[], 1020),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Alchemy', 'SDAM-09']::text[], 1030),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Allure', 'SDAL-02']::text[], 1040),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Allure', 'SDAL-03']::text[], 1050),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Allure', 'SDAL-04']::text[], 1060),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Cosmos', 'SDCS-01']::text[], 1070),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Cosmos', 'SDCS-02']::text[], 1080),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Cosmos', 'SDCS-03']::text[], 1090),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Cosmos', 'SDCS-05']::text[], 1100),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Dune', 'SDDN-01']::text[], 1110),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Dune', 'SDDN-02']::text[], 1120),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Dune', 'SDDN-03']::text[], 1130),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Dune', 'SDDN-04']::text[], 1140),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Dune', 'SDDN-05']::text[], 1150),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Essence', 'SDEC-01']::text[], 1160),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Essence', 'SDEC-02']::text[], 1170),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Essence', 'SDEC-03']::text[], 1180),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Essence', 'SDEC-04']::text[], 1190),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Essence', 'SDEC-05']::text[], 1200),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Lagos', 'SDLG-01']::text[], 1210),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Lagos', 'SDLG-02']::text[], 1220),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Lagos', 'SDLG-03']::text[], 1230),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Lagos', 'SDLG-04']::text[], 1240),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Lagos', 'SDLG-05']::text[], 1250),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Pyla', 'SDPL-01']::text[], 1260),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Pyla', 'SDPL-04']::text[], 1270),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Trinity', 'SDTR-01']::text[], 1280),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Trinity', 'SDTR-02']::text[], 1290),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Trinity', 'SDTR-04']::text[], 1300),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Opera', 'SCOPB-01']::text[], 1310),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Opera', 'SCOPB-03']::text[], 1320),
    ('Fabrics', 10, ARRAY['S-Contour', 'NBO', 'Opera', 'SCOP-01']::text[], 1330),
    ('Fabrics', 10, ARRAY['S-Contour', 'NBO', 'Opera', 'SCOP-02']::text[], 1340),
    ('Fabrics', 10, ARRAY['S-Contour', 'NBO', 'Opera', 'SCOP-03']::text[], 1350),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '558 Dark Grey']::text[], 1360),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '560 Black Brown']::text[], 1370),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '561 White Blue']::text[], 1380),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen Classic', '5%', '561 Black White']::text[], 1390),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Solaris (with Silver Backing)', 'SRS-301 White']::text[], 1400),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Solaris (with Silver Backing)', 'SRS-302 Beige']::text[], 1410),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Solaris (with Silver Backing)', 'SRS-303 Grey']::text[], 1420),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Panama', 'PN-01 White']::text[], 1430),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Panama', 'PN-02 Cream']::text[], 1440),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Panama', 'PN-03 Pearl']::text[], 1450),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Panama', 'PN-04 Beige']::text[], 1460),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Panama', 'PN-05 Brown']::text[], 1470),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Panama', 'PN-06 Chocolate']::text[], 1480),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Panama', 'PN-07 Grey']::text[], 1490),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Panama', 'PN-08 Charcoal']::text[], 1500),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent Celestial', '4%', '401 White']::text[], 1510),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent Celestial', '4%', '402 Ivory']::text[], 1520),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent Celestial', '4%', '403 Beige']::text[], 1530),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent Celestial', '4%', '404 Grey']::text[], 1540),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-10']::text[], 1550),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-20']::text[], 1560),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-25']::text[], 1570),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-28']::text[], 1580),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Translucent', 'Victorian', 'VIC-34']::text[], 1590),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Venice', 'Opaque-04']::text[], 1600),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Elena', '03']::text[], 1610),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Skyler', '03']::text[], 1620),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '11']::text[], 1630),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '12']::text[], 1640),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '13']::text[], 1650),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '14']::text[], 1660),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '15']::text[], 1670),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Blackout', 'Oribi', '16']::text[], 1680),
    ('Fabrics', 10, ARRAY['Roller Blind', 'Screen', 'Mellow', 'ML-06 Black']::text[], 1690),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Opera', 'SCOPB-02']::text[], 1700),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Croma Luxe', 'SCCL-01']::text[], 1710),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Croma Luxe', 'SCCL-02']::text[], 1720),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Croma Luxe', 'SCCL-03']::text[], 1730),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Croma Luxe', 'SCCL-04']::text[], 1740),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Dash Luxe', 'SCDX-01']::text[], 1750),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Dash Luxe', 'SCDX-02']::text[], 1760),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Dash Luxe', 'SCDX-03']::text[], 1770),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Dash Luxe', 'SCDX-04']::text[], 1780),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Diamond Luxe', 'SCDL-01']::text[], 1790),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Diamond Luxe', 'SCDL-02']::text[], 1800),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Diamond Luxe', 'SCDL-03']::text[], 1810),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Diamond Luxe', 'SCDL-04']::text[], 1820),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Diamond Luxe', 'SCDL-05']::text[], 1830),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Shadow Luxe', 'SCSL-01']::text[], 1840),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Shadow Luxe', 'SCSL-02']::text[], 1850),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Shadow Luxe', 'SCSL-03']::text[], 1860),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Shadow Luxe', 'SCSL-04']::text[], 1870),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Tri Luxe', 'SCTL-01']::text[], 1880),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Tri Luxe', 'SCTL-02']::text[], 1890),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Tri Luxe', 'SCTL-03']::text[], 1900),
    ('Fabrics', 10, ARRAY['S-Contour', 'Blackout', 'Tri Luxe', 'SCTL-04']::text[], 1910),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Silk', 'SDSS-01']::text[], 1920),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Silk', 'SDSS-02']::text[], 1930),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Silk', 'SDSS-03']::text[], 1940),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Silk', 'SDSS-04']::text[], 1950),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Silk', 'SDSS-05']::text[], 1960),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Pure', 'SDPS-01']::text[], 1970),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Pure', 'SDPS-02']::text[], 1980),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Pure', 'SDPS-03']::text[], 1990),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Pure', 'SDPS-04']::text[], 2000),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Pure', 'SDPS-05']::text[], 2010),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Pure', 'SDPS-06']::text[], 2020),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Silk', 'SDSK-01']::text[], 2030),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Silk', 'SDSK-02']::text[], 2040),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Silk', 'SDSK-03']::text[], 2050),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Silk', 'SDSK-04']::text[], 2060),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Mist Glow', 'SDMG-01']::text[], 2070),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Mist Glow', 'SDMG-02']::text[], 2080),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Mist Glow', 'SDMG-03']::text[], 2090),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Mist Glow', 'SDMG-04']::text[], 2100),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Mist Glow', 'SDMG-05']::text[], 2110),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Mist Glow', 'SDMG-06']::text[], 2120),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Glow', 'SDSG-01']::text[], 2130),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Glow', 'SDSG-02']::text[], 2140),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Glow', 'SDSG-03']::text[], 2150),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Glow', 'SDSG-04']::text[], 2160),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Soft Glow', 'SDSG-05']::text[], 2170),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Dawn Light', 'SDDL-01']::text[], 2180),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Dawn Light', 'SDDL-02']::text[], 2190),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Dawn Light', 'SDDL-03']::text[], 2200),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Dawn Light', 'SDDL-04']::text[], 2210),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Aura Veil', 'SDAV-01']::text[], 2220),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Aura Veil', 'SDAV-02']::text[], 2230),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Aura Veil', 'SDAV-03']::text[], 2240),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Aura Veil', 'SDAV-04']::text[], 2250),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Aura Veil', 'SDAV-05']::text[], 2260),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Aura Veil', 'SDAV-06']::text[], 2270),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Eco Luxe', 'SDEL-01']::text[], 2280),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Eco Luxe', 'SDEL-02']::text[], 2290),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Eco Luxe', 'SDEL-03']::text[], 2300),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Eco Luxe', 'SDEL-04']::text[], 2310),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Eco Luxe', 'SDEL-05']::text[], 2320),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Eco Luxe', 'SDEL-06']::text[], 2330),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Memphis', 'SDMS-01']::text[], 2340),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Memphis', 'SDMS-02']::text[], 2350),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Memphis', 'SDMS-03']::text[], 2360),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Memphis', 'SDMS-04']::text[], 2370),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Memphis', 'SDMS-05']::text[], 2380),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Sahara', 'SDSR-02']::text[], 2390),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Blackout', 'Sahara', 'SDSR-06']::text[], 2400),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Dune', 'SDDN-06']::text[], 2410),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Calm Waves', 'SDCW-01']::text[], 2420),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Calm Waves', 'SDCW-02']::text[], 2430),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Calm Waves', 'SDCW-03']::text[], 2440),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Calm Waves', 'SDCW-04']::text[], 2450),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Oasis', 'SDOA-01']::text[], 2460),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Oasis', 'SDOA-02']::text[], 2470),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Oasis', 'SDOA-03']::text[], 2480),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Oasis', 'SDOA-04']::text[], 2490),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Oasis', 'SDOA-05']::text[], 2500),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Oasis', 'SDOA-06']::text[], 2510),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Pyla', 'SDPL-02']::text[], 2520),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Pyla', 'SDPL-03']::text[], 2530),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Pyla', 'SDPL-05']::text[], 2540),
    ('Fabrics', 10, ARRAY['Sheer Dimout', 'Alchemy', 'SDAM-05']::text[], 2550),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'RUNNERS.']::text[], 2560),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'SPACERS.']::text[], 2570),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'P. CLIP']::text[], 2580),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'CONTROL UNIT.']::text[], 2590),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'TILT CHAIN LOCK']::text[], 2600),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'M.S. LOCK']::text[], 2610),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'ROD SUPPORT']::text[], 2620),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', '3 PCS SET']::text[], 2630),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'CORD DRIVE RUNNER']::text[], 2640),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'CORD WEIGHT']::text[], 2650),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'HANGERS.']::text[], 2660),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'C-LOCK.']::text[], 2670),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'SPACING TUBE']::text[], 2680),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'L BRACKET.']::text[], 2690),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'ALUMINIUM CHANNEL 4.572 MTR']::text[], 2700),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'TILT ROD 4.572 MTR.']::text[], 2710),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'BOTTOM WEIGHT NEW']::text[], 2720),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'CORD 2.2MM WHITE']::text[], 2730),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'BOTTOM CHAIN 4 INCH']::text[], 2740),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'TILTING CHAIN']::text[], 2750),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'SILICON SPRAY BOTTLE']::text[], 2760),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'STICKER VISTA']::text[], 2770),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'ROYAL PLUG 8X50']::text[], 2780),
    ('Parts', 20, ARRAY['Vertical Blinds Parts', 'ROYAL SCREW 8X50']::text[], 2790),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'ALUMINIUM ROLLER TUBE (4.575) 38 MM']::text[], 2800),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'ALU BOTTOM RAIL (4.575 MTR)']::text[], 2810),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'CONTROL UNIT KS 38 MM']::text[], 2820),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'Double Sided Fixon Tape 12MM']::text[], 2830),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'CORD WEIGHT']::text[], 2840),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'Connector - Bush Type']::text[], 2850),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'Bottom Rail End Cap']::text[], 2860),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'Operating Ball Chain']::text[], 2870),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'PVC INSERT 15MM']::text[], 2880),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'PVC INSERT 12 MM']::text[], 2890),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'Chain Stopper']::text[], 2900),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'ROYAL SCREW 8X50']::text[], 2910),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'ROYAL PLUG 8X50']::text[], 2920),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'Without Headrail', 'POLY TUBE 5"']::text[], 2930),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'ALU ROLLER TUBE 39MM (4.575 MTR)']::text[], 2940),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'ALU. ROUND BOTTOM RAIL(4.57 MTR)']::text[], 2950),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'ALU.HEADRAIL PATTI (4.575 MTR)']::text[], 2960),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'CONTROL UNIT 38MM']::text[], 2970),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'Double Sided Fixon Tape 12MM']::text[], 2980),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'CORD WEIGHT']::text[], 2990),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'Connector - Bush Type']::text[], 3000),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'Bottom Rail End Cap']::text[], 3010),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'Operating Ball Chain']::text[], 3020),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'PVC INSERT 15MM']::text[], 3030),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'PVC INSERT 12 MM']::text[], 3040),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'Chain Stopper']::text[], 3050),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'L BRACKET.']::text[], 3060),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'P. CLIP']::text[], 3070),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'ROYAL PLUG 8X50']::text[], 3080),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'ROYAL SCREW 8X50']::text[], 3090),
    ('Parts', 20, ARRAY['Roller Blind Parts', 'With Headrail', 'POLY TUBE 5"']::text[], 3100),
    ('Parts', 20, ARRAY['S-Contour Parts', 'ALU ROLLER TUBE 39MM (4.575 MTR)']::text[], 3110),
    ('Parts', 20, ARRAY['S-Contour Parts', 'ALU BOTTOM RAIL (4.575 MTR)']::text[], 3120),
    ('Parts', 20, ARRAY['S-Contour Parts', 'Alu. Headrail with Cover']::text[], 3130),
    ('Parts', 20, ARRAY['S-Contour Parts', 'CONTROL UNIT 38MM']::text[], 3140),
    ('Parts', 20, ARRAY['S-Contour Parts', 'End Less Chain']::text[], 3150),
    ('Parts', 20, ARRAY['S-Contour Parts', 'Bottom Rail End Cap']::text[], 3160),
    ('Parts', 20, ARRAY['S-Contour Parts', 'Chain Stopper']::text[], 3170),
    ('Parts', 20, ARRAY['S-Contour Parts', 'Metal End Cap']::text[], 3180),
    ('Parts', 20, ARRAY['S-Contour Parts', 'PVC SHEET WIDTH 87 MM']::text[], 3190),
    ('Parts', 20, ARRAY['S-Contour Parts', 'CEILING BRACKET']::text[], 3200),
    ('Parts', 20, ARRAY['S-Contour Parts', 'CORD WEIGHT']::text[], 3210),
    ('Parts', 20, ARRAY['S-Contour Parts', 'ROYAL SCREW 8X50']::text[], 3220),
    ('Parts', 20, ARRAY['S-Contour Parts', 'ROYAL PLUG 8X50']::text[], 3230),
    ('Parts', 20, ARRAY['S-Contour Parts', 'PVC INSERT 12 MM']::text[], 3240),
    ('Parts', 20, ARRAY['S-Contour Parts', 'Double Sided Fixon Tape 12MM']::text[], 3250),
    ('Parts', 20, ARRAY['S-Contour Parts', 'POLY TUBE 5"']::text[], 3260),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'ALU ROLLER TUBE 39MM (4.575 MTR)']::text[], 3270),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'ALU. ROUND BOTTOM RAIL(4.57 MTR)']::text[], 3280),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'ALU. TRIANGLE TYPE BOTTOM RAIL']::text[], 3290),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'Alu. Headrail with Cover']::text[], 3300),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'CONTROL UNIT KS 38 MM']::text[], 3310),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'End Less Chain']::text[], 3320),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'END CAP ROUND BOTTOM RAIL']::text[], 3330),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'END CAP TRIANGULAR BOTTOM RAIL']::text[], 3340),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'Metal End Cap']::text[], 3350),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'CEILLING BRACKET']::text[], 3360),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'CORD WEIGHT']::text[], 3370),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'ROYAL SCREW 8X50']::text[], 3380),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'ROYAL PLUG 8X50']::text[], 3390),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'P.V.C INSERT 10MM']::text[], 3400),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'PVC INSERT 12 MM']::text[], 3410),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'Double Sided Fixon Tape 12MM']::text[], 3420),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Plain Cassette', 'POLY TUBE 5"']::text[], 3430),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'ALU ROLLER TUBE 39MM (4.575 MTR)']::text[], 3440),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'ALU. ROUND BOTTOM RAIL(4.57 MTR)']::text[], 3450),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'ALU. U TYPE BOTTOM RAIL']::text[], 3460),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'CONTROL UNIT.']::text[], 3470),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'End Less Chain']::text[], 3480),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'END CAP ROUND BOTTOM RAIL']::text[], 3490),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'END CAP U TYPE BOTTOM RAIL']::text[], 3500),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'Metal End Cap']::text[], 3510),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'CEILLING BRACKET']::text[], 3520),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'CORD WEIGHT']::text[], 3530),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'P.V.C INSERT 10MM']::text[], 3540),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'PVC INSERT 12 MM']::text[], 3550),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'Double Sided Fixon Tape 12MM']::text[], 3560),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'POLY TUBE 5"']::text[], 3570),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'Alu. Headrail with Cover']::text[], 3580),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'Chain Stopper']::text[], 3590),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'PVC SHEET WIDTH 87 MM']::text[], 3600),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'ROYAL SCREW 8X50']::text[], 3610),
    ('Parts', 20, ARRAY['Sheer Dimout Parts', 'Decorative Cassette', 'ROYAL PLUG 8X50']::text[], 3620),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'Head Rail Aluminium']::text[], 3630),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'TILT ROD 4.572 MTR.']::text[], 3640),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'CONTROL UNIT.']::text[], 3650),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'Drum Holder']::text[], 3660),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'INSTALLATION BRACKET']::text[], 3670),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'CORD WEIGHT']::text[], 3680),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'M.S.Rod 4 MM']::text[], 3690),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'M.S.Rod 7 MM']::text[], 3700),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'CAP 4MM']::text[], 3710),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'CAP 7MM']::text[], 3720),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'CORD']::text[], 3730),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'D RING-RH 09 MM']::text[], 3740),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'ENDLESS CHAIN 3 MTR']::text[], 3750),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'VELCROW TAPE']::text[], 3760),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'ROYAL PLUG 8X50']::text[], 3770),
    ('Parts', 20, ARRAY['Roman Blinds Parts', 'ROYAL SCREW 8X50']::text[], 3780),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Super Track', 'SECTION NON-FERROUS SUPER TRACK']::text[], 3790),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Super Track', 'SUPER TRACK- RUNNER']::text[], 3800),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Super Track', 'BRACKET WALL SUPER TRACK']::text[], 3810),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Super Track', 'BRACKET CEILING-SUPER TRACK']::text[], 3820),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Super Track', 'END CAP SUPER TRACK']::text[], 3830),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Jumbo Track', 'AL SECTION NON-FERROUS JUMBO TRACK']::text[], 3840),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Jumbo Track', 'RUNNER FOR JUMBO TRACK']::text[], 3850),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Jumbo Track', 'BRACKET FOR JUMBO TRACK']::text[], 3860),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Jumbo Track', 'CEILING BRACKET FOR JUMBO TRACK']::text[], 3870),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'Jumbo Track', 'END CAP FOR JUMBO TRACK']::text[], 3880),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'M Track', 'ALU SECTION NON-FERROUS M TRACK']::text[], 3890),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'M Track', 'Runner for M Track']::text[], 3900),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'M Track', 'Bracket Wall for M Track']::text[], 3910),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'M Track', 'Bracket Ceiling for M Track']::text[], 3920),
    ('Tracks', 30, ARRAY['Curtain Tracks', 'M Track', 'End Cap for M Track']::text[], 3930),
    ('Motors', 40, ARRAY['Motors', 'Premium', 'Motor Premium (RTS)']::text[], 3940),
    ('Motors', 40, ARRAY['Motors', 'Premium', 'Remote Single Channel - Premium']::text[], 3950),
    ('Motors', 40, ARRAY['Motors', 'Premium', 'Remote 5 Channel - Premium']::text[], 3960)
    ) AS t(page_name, page_sort_order, path_names, sort_base)
  LOOP
    v_page_id := public.ensure_master_page_seed(rec.page_name, rec.page_sort_order);
    v_parent_id := NULL;

    FOR v_idx IN 1..array_length(rec.path_names, 1) LOOP
      v_name := rec.path_names[v_idx];
      v_normalized := public.normalize_master_seed_name(v_name);

      IF v_parent_id IS NULL THEN
        SELECT id INTO v_node_id
        FROM public.master_nodes
        WHERE parent_id IS NULL AND normalized_name = v_normalized
        LIMIT 1;
      ELSE
        SELECT id INTO v_node_id
        FROM public.master_nodes
        WHERE parent_id = v_parent_id AND normalized_name = v_normalized
        LIMIT 1;
      END IF;

      IF v_node_id IS NULL THEN
        INSERT INTO public.master_nodes(parent_id, name, normalized_name, exclude_from_pnc_name, sort_order)
        VALUES (v_parent_id, v_name, v_normalized, FALSE, rec.sort_base + v_idx)
        RETURNING id INTO v_node_id;
      ELSE
        UPDATE public.master_nodes
        SET name = v_name
        WHERE id = v_node_id AND name IS DISTINCT FROM v_name;
      END IF;

      IF v_idx = 1 THEN
        UPDATE public.master_nodes
        SET page_id = v_page_id
        WHERE id = v_node_id AND page_id IS DISTINCT FROM v_page_id;
      END IF;

      v_parent_id := v_node_id;
    END LOOP;
  END LOOP;
END;
$$;
