-- Product code catalog imported from Excel File/Product Codes.xlsx
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS public.product_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_category TEXT NOT NULL,
  code TEXT NOT NULL,
  normalized_code TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS product_codes_normalized_code_key ON public.product_codes (normalized_code);
ALTER TABLE IF EXISTS public.order_items ADD COLUMN IF NOT EXISTS product_code_id UUID REFERENCES public.product_codes(id) ON DELETE SET NULL;
ALTER TABLE IF EXISTS public.order_items ADD COLUMN IF NOT EXISTS product_name TEXT;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_codes TO authenticated;
ALTER TABLE public.product_codes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS product_codes_read ON public.product_codes;
DROP POLICY IF EXISTS product_codes_admin_write ON public.product_codes;
CREATE POLICY product_codes_read ON public.product_codes FOR SELECT TO authenticated USING (true);
CREATE POLICY product_codes_admin_write ON public.product_codes FOR ALL TO authenticated USING (public.current_app_role() = 'admin') WITH CHECK (public.current_app_role() = 'admin');
INSERT INTO public.product_codes (stock_category, code, normalized_code) VALUES
  ('Roller Blinds', 'Roller Blind Blackout Bamberg 01', 'roller blind blackout bamberg 01'),
  ('Roller Blinds', 'Roller Blind Blackout Bamberg 02', 'roller blind blackout bamberg 02'),
  ('Roller Blinds', 'Roller Blind Blackout Bamberg 03', 'roller blind blackout bamberg 03'),
  ('Roller Blinds', 'Roller Blind Blackout Bamberg 04', 'roller blind blackout bamberg 04'),
  ('Roller Blinds', 'Roller Blind Blackout Bamberg 05', 'roller blind blackout bamberg 05'),
  ('Roller Blinds', 'Roller Blind Blackout Cloudnine CN-01 White', 'roller blind blackout cloudnine cn-01 white'),
  ('Roller Blinds', 'Roller Blind Blackout Cloudnine CN-02 Ivory', 'roller blind blackout cloudnine cn-02 ivory'),
  ('Roller Blinds', 'Roller Blind Blackout Cloudnine CN-03 Grey', 'roller blind blackout cloudnine cn-03 grey'),
  ('Roller Blinds', 'Roller Blind Blackout DS Opaque Champagne', 'roller blind blackout ds opaque champagne'),
  ('Roller Blinds', 'Roller Blind Blackout DS Opaque Fawn', 'roller blind blackout ds opaque fawn'),
  ('Roller Blinds', 'Roller Blind Blackout DS Opaque Grey', 'roller blind blackout ds opaque grey'),
  ('Roller Blinds', 'Roller Blind Blackout DS Opaque Linen', 'roller blind blackout ds opaque linen'),
  ('Roller Blinds', 'Roller Blind Blackout DS Opaque White', 'roller blind blackout ds opaque white'),
  ('Roller Blinds', 'Roller Blind Blackout Elena 01', 'roller blind blackout elena 01'),
  ('Roller Blinds', 'Roller Blind Blackout Elena 02', 'roller blind blackout elena 02'),
  ('Roller Blinds', 'Roller Blind Blackout Elena 03', 'roller blind blackout elena 03'),
  ('Roller Blinds', 'Roller Blind Blackout Elena 04', 'roller blind blackout elena 04'),
  ('Roller Blinds', 'Roller Blind Blackout Elena 05', 'roller blind blackout elena 05'),
  ('Roller Blinds', 'Roller Blind Blackout Murano Opaque-01', 'roller blind blackout murano opaque-01'),
  ('Roller Blinds', 'Roller Blind Blackout Murano Opaque-03', 'roller blind blackout murano opaque-03'),
  ('Roller Blinds', 'Roller Blind Blackout Murano Opaque-05', 'roller blind blackout murano opaque-05'),
  ('Roller Blinds', 'Roller Blind Blackout Murano Opaque-07', 'roller blind blackout murano opaque-07'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 01', 'roller blind blackout oribi 01'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 02', 'roller blind blackout oribi 02'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 03', 'roller blind blackout oribi 03'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 04', 'roller blind blackout oribi 04'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 05', 'roller blind blackout oribi 05'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 06', 'roller blind blackout oribi 06'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 07', 'roller blind blackout oribi 07'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 08', 'roller blind blackout oribi 08'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 09', 'roller blind blackout oribi 09'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 10', 'roller blind blackout oribi 10'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 11', 'roller blind blackout oribi 11'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 12', 'roller blind blackout oribi 12'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 13', 'roller blind blackout oribi 13'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 14', 'roller blind blackout oribi 14'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 15', 'roller blind blackout oribi 15'),
  ('Roller Blinds', 'Roller Blind Blackout Oribi 16', 'roller blind blackout oribi 16'),
  ('Roller Blinds', 'Roller Blind Blackout Serene Opaque-01 White', 'roller blind blackout serene opaque-01 white'),
  ('Roller Blinds', 'Roller Blind Blackout Serene Opaque-02 Beige', 'roller blind blackout serene opaque-02 beige'),
  ('Roller Blinds', 'Roller Blind Blackout Serene Opaque-03 Sand', 'roller blind blackout serene opaque-03 sand'),
  ('Roller Blinds', 'Roller Blind Blackout Serene Opaque-04 Grey', 'roller blind blackout serene opaque-04 grey'),
  ('Roller Blinds', 'Roller Blind Blackout Skyler 01', 'roller blind blackout skyler 01'),
  ('Roller Blinds', 'Roller Blind Blackout Skyler 02', 'roller blind blackout skyler 02'),
  ('Roller Blinds', 'Roller Blind Blackout Skyler 03', 'roller blind blackout skyler 03'),
  ('Roller Blinds', 'Roller Blind Blackout Skyler 04', 'roller blind blackout skyler 04'),
  ('Roller Blinds', 'Roller Blind Blackout Skyler 05', 'roller blind blackout skyler 05'),
  ('Roller Blinds', 'Roller Blind Blackout Skyler 06', 'roller blind blackout skyler 06'),
  ('Roller Blinds', 'Roller Blind Blackout Venice Opaque-01', 'roller blind blackout venice opaque-01'),
  ('Roller Blinds', 'Roller Blind Blackout Venice Opaque-02', 'roller blind blackout venice opaque-02'),
  ('Roller Blinds', 'Roller Blind Blackout Venice Opaque-03', 'roller blind blackout venice opaque-03'),
  ('Roller Blinds', 'Roller Blind Blackout Venice Opaque-04', 'roller blind blackout venice opaque-04'),
  ('Roller Blinds', 'Roller Blind Blackout Venice Opaque-05', 'roller blind blackout venice opaque-05'),
  ('Roller Blinds', 'Roller Blind Blackout Venice Opaque-06', 'roller blind blackout venice opaque-06'),
  ('Roller Blinds', 'Roller Blind Blackout Violet 01', 'roller blind blackout violet 01'),
  ('Roller Blinds', 'Roller Blind Blackout Violet 02', 'roller blind blackout violet 02'),
  ('Roller Blinds', 'Roller Blind Blackout Violet 03', 'roller blind blackout violet 03'),
  ('Roller Blinds', 'Roller Blind Blackout Violet 04', 'roller blind blackout violet 04'),
  ('Roller Blinds', 'Roller Blind Blackout Violet 05', 'roller blind blackout violet 05'),
  ('Roller Blinds', 'Roller Blind Screen Classic 1% 111 White', 'roller blind screen classic 1% 111 white'),
  ('Roller Blinds', 'Roller Blind Screen Classic 1% 112 Beige', 'roller blind screen classic 1% 112 beige'),
  ('Roller Blinds', 'Roller Blind Screen Classic 1% 113 Grey', 'roller blind screen classic 1% 113 grey'),
  ('Roller Blinds', 'Roller Blind Screen Classic 3% 331 White', 'roller blind screen classic 3% 331 white'),
  ('Roller Blinds', 'Roller Blind Screen Classic 3% 332 Beige', 'roller blind screen classic 3% 332 beige'),
  ('Roller Blinds', 'Roller Blind Screen Classic 3% 334 Grey', 'roller blind screen classic 3% 334 grey'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 551 White', 'roller blind screen classic 5% 551 white'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 552 Fawn', 'roller blind screen classic 5% 552 fawn'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 554 Grey', 'roller blind screen classic 5% 554 grey'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 556 Black Grey', 'roller blind screen classic 5% 556 black grey'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 557 Light Grey', 'roller blind screen classic 5% 557 light grey'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 558 Dark Grey', 'roller blind screen classic 5% 558 dark grey'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 560 Black Brown', 'roller blind screen classic 5% 560 black brown'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 561 Black White', 'roller blind screen classic 5% 561 black white'),
  ('Roller Blinds', 'Roller Blind Screen Classic 5% 561 White Blue', 'roller blind screen classic 5% 561 white blue'),
  ('Roller Blinds', 'Roller Blind Screen Mellow ML-01 White', 'roller blind screen mellow ml-01 white'),
  ('Roller Blinds', 'Roller Blind Screen Mellow ML-02 Ivory', 'roller blind screen mellow ml-02 ivory'),
  ('Roller Blinds', 'Roller Blind Screen Mellow ML-03 Beige', 'roller blind screen mellow ml-03 beige'),
  ('Roller Blinds', 'Roller Blind Screen Mellow ML-04 Chocolate', 'roller blind screen mellow ml-04 chocolate'),
  ('Roller Blinds', 'Roller Blind Screen Mellow ML-05 Grey', 'roller blind screen mellow ml-05 grey'),
  ('Roller Blinds', 'Roller Blind Screen Mellow ML-06 Black', 'roller blind screen mellow ml-06 black'),
  ('Roller Blinds', 'Roller Blind Screen Solaris (with Silver Backing) SRS-301 White', 'roller blind screen solaris (with silver backing) srs-301 white'),
  ('Roller Blinds', 'Roller Blind Screen Solaris (with Silver Backing) SRS-302 Beige', 'roller blind screen solaris (with silver backing) srs-302 beige'),
  ('Roller Blinds', 'Roller Blind Screen Solaris (with Silver Backing) SRS-303 Grey', 'roller blind screen solaris (with silver backing) srs-303 grey'),
  ('Roller Blinds', 'Roller Blind Surge SG-01', 'roller blind surge sg-01'),
  ('Roller Blinds', 'Roller Blind Surge SG-04', 'roller blind surge sg-04'),
  ('Roller Blinds', 'Roller Blind Surge SG-05', 'roller blind surge sg-05'),
  ('Roller Blinds', 'Roller Blind Translucent Celestial 4% 401 White', 'roller blind translucent celestial 4% 401 white'),
  ('Roller Blinds', 'Roller Blind Translucent Celestial 4% 402 Ivory', 'roller blind translucent celestial 4% 402 ivory'),
  ('Roller Blinds', 'Roller Blind Translucent Celestial 4% 403 Beige', 'roller blind translucent celestial 4% 403 beige'),
  ('Roller Blinds', 'Roller Blind Translucent Celestial 4% 404 Grey', 'roller blind translucent celestial 4% 404 grey'),
  ('Roller Blinds', 'Roller Blind Translucent Panama PN-01 White', 'roller blind translucent panama pn-01 white'),
  ('Roller Blinds', 'Roller Blind Translucent Panama PN-02 Cream', 'roller blind translucent panama pn-02 cream'),
  ('Roller Blinds', 'Roller Blind Translucent Panama PN-03 Pearl', 'roller blind translucent panama pn-03 pearl'),
  ('Roller Blinds', 'Roller Blind Translucent Panama PN-04 Beige', 'roller blind translucent panama pn-04 beige'),
  ('Roller Blinds', 'Roller Blind Translucent Panama PN-05 Brown', 'roller blind translucent panama pn-05 brown'),
  ('Roller Blinds', 'Roller Blind Translucent Panama PN-06 Chocolate', 'roller blind translucent panama pn-06 chocolate'),
  ('Roller Blinds', 'Roller Blind Translucent Panama PN-07 Grey', 'roller blind translucent panama pn-07 grey'),
  ('Roller Blinds', 'Roller Blind Translucent Panama PN-08 Charcoal', 'roller blind translucent panama pn-08 charcoal'),
  ('Roller Blinds', 'Roller Blind Translucent Serene NBO 01 White', 'roller blind translucent serene nbo 01 white'),
  ('Roller Blinds', 'Roller Blind Translucent Serene NBO 02 Beige', 'roller blind translucent serene nbo 02 beige'),
  ('Roller Blinds', 'Roller Blind Translucent Serene NBO 03 Sand', 'roller blind translucent serene nbo 03 sand'),
  ('Roller Blinds', 'Roller Blind Translucent Serene NBO 04 Grey', 'roller blind translucent serene nbo 04 grey'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-01', 'roller blind translucent victorian vic-01'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-03', 'roller blind translucent victorian vic-03'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-09', 'roller blind translucent victorian vic-09'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-10', 'roller blind translucent victorian vic-10'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-16', 'roller blind translucent victorian vic-16'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-20', 'roller blind translucent victorian vic-20'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-25', 'roller blind translucent victorian vic-25'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-28', 'roller blind translucent victorian vic-28'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-31', 'roller blind translucent victorian vic-31'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-33', 'roller blind translucent victorian vic-33'),
  ('Roller Blinds', 'Roller Blind Translucent Victorian VIC-34', 'roller blind translucent victorian vic-34'),
  ('Roller Blinds', 'Roller Blind Translucent Torrent TR-03 Light Grey', 'roller blind translucent torrent tr-03 light grey'),
  ('S-Contour', 'S-Contour Croma Luxe Blackout SCCL-01', 's-contour croma luxe blackout sccl-01'),
  ('S-Contour', 'S-Contour Croma Luxe Blackout SCCL-02', 's-contour croma luxe blackout sccl-02'),
  ('S-Contour', 'S-Contour Croma Luxe Blackout SCCL-03', 's-contour croma luxe blackout sccl-03'),
  ('S-Contour', 'S-Contour Croma Luxe Blackout SCCL-04', 's-contour croma luxe blackout sccl-04'),
  ('S-Contour', 'S-Contour Dash Luxe Blackout SCDX-01', 's-contour dash luxe blackout scdx-01'),
  ('S-Contour', 'S-Contour Dash Luxe Blackout SCDX-02', 's-contour dash luxe blackout scdx-02'),
  ('S-Contour', 'S-Contour Dash Luxe Blackout SCDX-03', 's-contour dash luxe blackout scdx-03'),
  ('S-Contour', 'S-Contour Dash Luxe Blackout SCDX-04', 's-contour dash luxe blackout scdx-04'),
  ('S-Contour', 'S-Contour Diamond Luxe Blackout SCDL-01', 's-contour diamond luxe blackout scdl-01'),
  ('S-Contour', 'S-Contour Diamond Luxe Blackout SCDL-02', 's-contour diamond luxe blackout scdl-02'),
  ('S-Contour', 'S-Contour Diamond Luxe Blackout SCDL-03', 's-contour diamond luxe blackout scdl-03'),
  ('S-Contour', 'S-Contour Diamond Luxe Blackout SCDL-04', 's-contour diamond luxe blackout scdl-04'),
  ('S-Contour', 'S-Contour Diamond Luxe Blackout SCDL-05', 's-contour diamond luxe blackout scdl-05'),
  ('S-Contour', 'S-Contour Opera Blackout SCOPB-01', 's-contour opera blackout scopb-01'),
  ('S-Contour', 'S-Contour Opera Blackout SCOPB-02', 's-contour opera blackout scopb-02'),
  ('S-Contour', 'S-Contour Opera Blackout SCOPB-03', 's-contour opera blackout scopb-03'),
  ('S-Contour', 'S-Contour Opera NBO SCOP-01', 's-contour opera nbo scop-01'),
  ('S-Contour', 'S-Contour Opera NBO SCOP-02', 's-contour opera nbo scop-02'),
  ('S-Contour', 'S-Contour Opera NBO SCOP-03', 's-contour opera nbo scop-03'),
  ('S-Contour', 'S-Contour Shadow Luxe Blackout SCSL-01', 's-contour shadow luxe blackout scsl-01'),
  ('S-Contour', 'S-Contour Shadow Luxe Blackout SCSL-02', 's-contour shadow luxe blackout scsl-02'),
  ('S-Contour', 'S-Contour Shadow Luxe Blackout SCSL-03', 's-contour shadow luxe blackout scsl-03'),
  ('S-Contour', 'S-Contour Shadow Luxe Blackout SCSL-04', 's-contour shadow luxe blackout scsl-04'),
  ('S-Contour', 'S-Contour Tri Luxe Blackout SCTL-01', 's-contour tri luxe blackout sctl-01'),
  ('S-Contour', 'S-Contour Tri Luxe Blackout SCTL-02', 's-contour tri luxe blackout sctl-02'),
  ('S-Contour', 'S-Contour Tri Luxe Blackout SCTL-03', 's-contour tri luxe blackout sctl-03'),
  ('S-Contour', 'S-Contour Tri Luxe Blackout SCTL-04', 's-contour tri luxe blackout sctl-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Alchemy SDAM-01', 'sheer dimout alchemy sdam-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Alchemy SDAM-02', 'sheer dimout alchemy sdam-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Alchemy SDAM-03', 'sheer dimout alchemy sdam-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Alchemy SDAM-05', 'sheer dimout alchemy sdam-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Alchemy SDAM-07', 'sheer dimout alchemy sdam-07'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Alchemy SDAM-08', 'sheer dimout alchemy sdam-08'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Alchemy SDAM-09', 'sheer dimout alchemy sdam-09'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Allure SDAL-02', 'sheer dimout allure sdal-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Allure SDAL-03', 'sheer dimout allure sdal-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Allure SDAL-04', 'sheer dimout allure sdal-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Aura Veil Blackout SDAV-01', 'sheer dimout aura veil blackout sdav-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Aura Veil Blackout SDAV-02', 'sheer dimout aura veil blackout sdav-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Aura Veil Blackout SDAV-03', 'sheer dimout aura veil blackout sdav-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Aura Veil Blackout SDAV-04', 'sheer dimout aura veil blackout sdav-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Aura Veil Blackout SDAV-05', 'sheer dimout aura veil blackout sdav-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Aura Veil Blackout SDAV-06', 'sheer dimout aura veil blackout sdav-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Calm Waves SDCW-01', 'sheer dimout calm waves sdcw-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Calm Waves SDCW-02', 'sheer dimout calm waves sdcw-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Calm Waves SDCW-03', 'sheer dimout calm waves sdcw-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Calm Waves SDCW-04', 'sheer dimout calm waves sdcw-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Cosmos SDCS-01', 'sheer dimout cosmos sdcs-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Cosmos SDCS-02', 'sheer dimout cosmos sdcs-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Cosmos SDCS-03', 'sheer dimout cosmos sdcs-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Cosmos SDCS-05', 'sheer dimout cosmos sdcs-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dawn Light Blackout SDDL-01', 'sheer dimout dawn light blackout sddl-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dawn Light Blackout SDDL-02', 'sheer dimout dawn light blackout sddl-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dawn Light Blackout SDDL-03', 'sheer dimout dawn light blackout sddl-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dawn Light Blackout SDDL-04', 'sheer dimout dawn light blackout sddl-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Denver Blackout SDDR-02', 'sheer dimout denver blackout sddr-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Denver Blackout SDDR-03', 'sheer dimout denver blackout sddr-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Denver Blackout SDDR-04', 'sheer dimout denver blackout sddr-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dune SDDN-01', 'sheer dimout dune sddn-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dune SDDN-02', 'sheer dimout dune sddn-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dune SDDN-03', 'sheer dimout dune sddn-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dune SDDN-04', 'sheer dimout dune sddn-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dune SDDN-05', 'sheer dimout dune sddn-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Dune SDDN-06', 'sheer dimout dune sddn-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Eco Luxe Blackout SDEL-01', 'sheer dimout eco luxe blackout sdel-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Eco Luxe Blackout SDEL-02', 'sheer dimout eco luxe blackout sdel-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Eco Luxe Blackout SDEL-03', 'sheer dimout eco luxe blackout sdel-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Eco Luxe Blackout SDEL-04', 'sheer dimout eco luxe blackout sdel-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Eco Luxe Blackout SDEL-05', 'sheer dimout eco luxe blackout sdel-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Eco Luxe Blackout SDEL-06', 'sheer dimout eco luxe blackout sdel-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Essence SDEC-01', 'sheer dimout essence sdec-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Essence SDEC-02', 'sheer dimout essence sdec-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Essence SDEC-03', 'sheer dimout essence sdec-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Essence SDEC-04', 'sheer dimout essence sdec-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Essence SDEC-05', 'sheer dimout essence sdec-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Lagos SDLG-01', 'sheer dimout lagos sdlg-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Lagos SDLG-02', 'sheer dimout lagos sdlg-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Lagos SDLG-03', 'sheer dimout lagos sdlg-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Lagos SDLG-04', 'sheer dimout lagos sdlg-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Lagos SDLG-05', 'sheer dimout lagos sdlg-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Memphis Blackout SDMS-01', 'sheer dimout memphis blackout sdms-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Memphis Blackout SDMS-02', 'sheer dimout memphis blackout sdms-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Memphis Blackout SDMS-03', 'sheer dimout memphis blackout sdms-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Memphis Blackout SDMS-04', 'sheer dimout memphis blackout sdms-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Memphis Blackout SDMS-05', 'sheer dimout memphis blackout sdms-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Mist Glow Blackout SDMG-01', 'sheer dimout mist glow blackout sdmg-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Mist Glow Blackout SDMG-02', 'sheer dimout mist glow blackout sdmg-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Mist Glow Blackout SDMG-03', 'sheer dimout mist glow blackout sdmg-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Mist Glow Blackout SDMG-04', 'sheer dimout mist glow blackout sdmg-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Mist Glow Blackout SDMG-05', 'sheer dimout mist glow blackout sdmg-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Mist Glow Blackout SDMG-06', 'sheer dimout mist glow blackout sdmg-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Novel SDNB-01', 'sheer dimout novel sdnb-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Novel SDNB-02', 'sheer dimout novel sdnb-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Novel SDNB-03', 'sheer dimout novel sdnb-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Novel SDNB-04', 'sheer dimout novel sdnb-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Novel SDNB-05', 'sheer dimout novel sdnb-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Novel SDNB-06', 'sheer dimout novel sdnb-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Oasis SDOA-01', 'sheer dimout oasis sdoa-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Oasis SDOA-02', 'sheer dimout oasis sdoa-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Oasis SDOA-03', 'sheer dimout oasis sdoa-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Oasis SDOA-04', 'sheer dimout oasis sdoa-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Oasis SDOA-05', 'sheer dimout oasis sdoa-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Oasis SDOA-06', 'sheer dimout oasis sdoa-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pure Blackout SDPS-01', 'sheer dimout pure blackout sdps-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pure Blackout SDPS-02', 'sheer dimout pure blackout sdps-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pure Blackout SDPS-03', 'sheer dimout pure blackout sdps-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pure Blackout SDPS-04', 'sheer dimout pure blackout sdps-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pure Blackout SDPS-05', 'sheer dimout pure blackout sdps-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pure Blackout SDPS-06', 'sheer dimout pure blackout sdps-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pyla SDPL-01', 'sheer dimout pyla sdpl-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pyla SDPL-02', 'sheer dimout pyla sdpl-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pyla SDPL-03', 'sheer dimout pyla sdpl-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pyla SDPL-04', 'sheer dimout pyla sdpl-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Pyla SDPL-05', 'sheer dimout pyla sdpl-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Sahara Blackout SDSR-01', 'sheer dimout sahara blackout sdsr-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Sahara Blackout SDSR-02', 'sheer dimout sahara blackout sdsr-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Sahara Blackout SDSR-03', 'sheer dimout sahara blackout sdsr-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Sahara Blackout SDSR-04', 'sheer dimout sahara blackout sdsr-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Sahara Blackout SDSR-05', 'sheer dimout sahara blackout sdsr-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Sahara Blackout SDSR-06', 'sheer dimout sahara blackout sdsr-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Sahara Blackout SDSR-07', 'sheer dimout sahara blackout sdsr-07'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Silk Blackout SDSS-01', 'sheer dimout silk blackout sdss-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Silk Blackout SDSS-02', 'sheer dimout silk blackout sdss-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Silk Blackout SDSS-03', 'sheer dimout silk blackout sdss-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Silk Blackout SDSS-04', 'sheer dimout silk blackout sdss-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Silk Blackout SDSS-05', 'sheer dimout silk blackout sdss-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Glow Blackout SDSG-01', 'sheer dimout soft glow blackout sdsg-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Glow Blackout SDSG-02', 'sheer dimout soft glow blackout sdsg-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Glow Blackout SDSG-03', 'sheer dimout soft glow blackout sdsg-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Glow Blackout SDSG-04', 'sheer dimout soft glow blackout sdsg-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Glow Blackout SDSG-05', 'sheer dimout soft glow blackout sdsg-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Silk Blackout SDSK-01', 'sheer dimout soft silk blackout sdsk-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Silk Blackout SDSK-02', 'sheer dimout soft silk blackout sdsk-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Silk Blackout SDSK-03', 'sheer dimout soft silk blackout sdsk-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Soft Silk Blackout SDSK-04', 'sheer dimout soft silk blackout sdsk-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Thar Blackout SDTH-03', 'sheer dimout thar blackout sdth-03'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Thar Blackout SDTH-04', 'sheer dimout thar blackout sdth-04'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Thar Blackout SDTH-05', 'sheer dimout thar blackout sdth-05'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Thar Blackout SDTH-06', 'sheer dimout thar blackout sdth-06'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Trinity SDTR-01', 'sheer dimout trinity sdtr-01'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Trinity SDTR-02', 'sheer dimout trinity sdtr-02'),
  ('Sheer Dimout Blinds', 'Sheer Dimout Trinity SDTR-04', 'sheer dimout trinity sdtr-04')
ON CONFLICT (normalized_code) DO UPDATE SET stock_category = EXCLUDED.stock_category, code = EXCLUDED.code, updated_at = now();
SELECT COUNT(*) AS product_codes FROM public.product_codes;
